import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex justify-center items-center flex-row gap-5 p-12"> 
          <div>
            <Link href="/"> Home</Link>
          </div>
          <div>
            <Link href="/about"> About</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
